#!/bin/bash

# LDAP Configuration Setup
echo "=== LDAP Configuration Setup ==="

## Prompt for LDAP server
echo -n "Enter LDAP server URL (e.g., ldaps://ldap.company.com:636): "
read ldap_server

## Prompt for LDAP base DN
echo -n "Enter LDAP base DN (e.g., DC=company,DC=com): "
read base_dn

## Prompt for LDAP username
echo -n "Enter LDAP username (e.g., corp\\\\me123): "
read ldap_user

## Prompt for LDAP password
echo -n "Enter LDAP password: "
read -s ldap_password
echo

# Ensure the bin directory exists
mkdir -p ./bin

# Save the credentials and configuration to a file
echo "# LDAP Configuration - Generated by task.setup.sh" > ./bin/.ldap_credentials
echo "export ldap_server=\"$ldap_server\"" >> ./bin/.ldap_credentials
echo "export base_dn=\"$base_dn\"" >> ./bin/.ldap_credentials
echo "export ldap_user=\"$ldap_user\"" >> ./bin/.ldap_credentials
echo "export ldap_password=\"$ldap_password\"" >> ./bin/.ldap_credentials

# Set secure permissions on the credentials file
chmod 600 ./bin/.ldap_credentials

echo "LDAP configuration saved to ./bin/.ldap_credentials"
echo "Setup complete."